// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import ()

type Message struct {
	ID         int32  `db:"id" json:"id"`
	Message    string `db:"message" json:"message"`
	SenderID   int32  `db:"sender_id" json:"sender_id"`
	ReceiverID int32  `db:"receiver_id" json:"receiver_id"`
}

type User struct {
	ID   int32  `db:"id" json:"id"`
	Name string `db:"name" json:"name"`
}
