// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"database/sql"
)

type User struct {
	ID   int32          `db:"id" json:"id"`
	Name sql.NullString `db:"name" json:"name"`
}
